version: '2'
services:
  vp0:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=vp0
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      - CORE_LOGGING_LEVEL=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "peer node start "

  vp1:
    extends: vp0
    environment:
      - CORE_PEER_ID=vp1
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    command: sh -c "peer node start "
  vp2:
    extends: vp0
    environment:
      - CORE_PEER_ID=vp2
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    command: sh -c "peer node start "
  vp3:
    extends: vp0
    environment:
      - CORE_PEER_ID=vp3
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    ports:
      - 7050-7053:7050-7053
    command: sh -c "peer node start "