version: '3'
services:
  vp0:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=vp0
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
#      - CORE_LOGGING_LEVEL=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "peer node start "
    networks:
      - peer_net
    deploy:
      placement:
        constraints: [node.role == manager]

  vp1:
    environment:
      - CORE_PEER_ID=vp1
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
    Volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "peer node start "
    networks:
      - peer_net
  vp2:
    environment:
      - CORE_PEER_ID=vp2
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "peer node start "
    networks:
      - peer_net
  vp3:
    environment:
      - CORE_PEER_ID=vp3
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "peer node start "
    networks:
      - peer_net
  vp4:
    environment:
      - CORE_PEER_ID=vp4
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "peer node start "
    networks:
      - peer_net
  vp5:
    environment:
      - CORE_PEER_ID=vp5
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "peer node start "
    networks:
      - peer_net
  vp6:
    environment:
      - CORE_PEER_ID=vp6
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "peer node start "
    networks:
      - peer_net
  vp7:
    environment:
      - CORE_PEER_ID=vp7
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "peer node start "
    networks:
      - peer_net

networks:
    peer_net:
